config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  get 'about', to: 'about#index'
  get 'admin', to: 'posts#admin'
  resources :posts
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :find_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticate, only: [:admin, :new, :create, :edit, :update, :destroy]

    def index
        if params[:category].blank?
            @category_id = Category.find_by(name: 'Hidden').id
            @posts = Post.where.not(category_id: @category_id).order("created_at DESC")          
        else
            @category_id = Category.find_by(name: params[:category]).id
            if params[:category] == "Hidden"
                @posts = Post.where(category_id: @category_id).order("created_at DESC") if authenticate
            else
                @posts = Post.where(category_id: @category_id).order("created_at DESC")
            end
        end
    end

    def show
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)

        if @post.save
            redirect_to @post, notice: "The post was created!"
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @post.update(post_params)
            redirect_to @post, notice: "Update successful"
        else
            render ‘edit’
        end
    end

    def destroy
        @post.destroy
        redirect_to root_path, notice: "Post destroyed"
    end

    def admin
        redirect_to root_path if authenticate
    end

private
    def post_params
        params.require(:post).permit(:title, :author, :content, :category_id, :image)
    end

    def find_post
        @post = Post.find(params[:id])
    end
end

protected_methods
    def authenticate
        authenticate_or_request_with_http_basic do |username, password|
        admin_username= Rails.application.credentials[:admin_username]
        admin_password= Rails.application.credentials[:admin_password]

        session[:admin] = true if (username == admin_username && password == admin_password)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about/index.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>

<%= render 'shared/nav' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdn.quilljs.com/1.1.9/quill.js"></script>
    <link href="https://cdn.quilljs.com/1.1.9/quill.snow.css" rel="stylesheet">
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>

    <%= render "shared/error_messages" %>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {prompt: "Choose a category" }) %><br>
    <%= f.label :title %><br>
    <%= f.text_field :title, placeholder: "Type the post title here" %><br>
    <%= f.label :author %><br>
    <%= f.text_field :author, placeholder: "Type the post author here" %><br>
    <%= f.label :content %><br>
    <%= f.text_area :content, class: 'quill_container', placeholder: "Type the post text here" %><br>
    <%= f.label :image %><br>
    <%= f.file_field :image %><br>

    <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>
<%= link_to "Back", root_path %>

app/views/posts/index.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>

<%= render 'shared/nav' %>


<div class="container h-100">

  <div class="row h-100 justify-content-center align-items-center">
    <% @posts.each do |post| %>
    <!-- Post Content Column -->
    <!-- Preview Image -->
    <%= image_tag post.image_url.to_s, alt: "Image", class: "img-fluid" %>
    <div class="col-lg-10">

      <!-- Title -->
      <h1 class="mt-4 headline"><%= link_to post.title, post %></h1>

      <!-- Author/Date/Time -->
      <p class="authdate">by <%= post.author %><br>
        Posted on <%= post.created_at.strftime("%B %d, %Y") %></p>

      <hr>

      <!-- Post Content -->
      <div class="content"><%= post.content.first(1000).gsub("<p><br></p>","").html_safe + "..."%></div>
      <hr>
    </div>
    <% end %>
  </div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render "form" %>
<%= link_to "Back", root_path %>

app/views/posts/show.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>

<%= render 'shared/nav' %>

<div class="container h-100">

  <div class="row h-100 justify-content-center align-items-center">

    <!-- Preview Image -->
    <%= image_tag @post.image_url.to_s, alt: "Image", class: "img-fluid" %>

    <!-- Post Content Column -->
    <div class="col-lg-10">

      <!-- Title -->
      <h1 class="mt-4 headline"><%= @post.title %></h1>

      <!-- Author/Date/Time -->
      <p class="authdate">by <%= @post.author %><br>
        Posted on <%= @post.created_at.strftime("%B %d, %Y") %></p>

      <hr>

      <!-- Post Content -->
      <div class="content"><%= @post.content.gsub("<p><br></p>","").html_safe %></div>


      <!-- Admin Buttons -->
      <% if session[:admin] then %>
      <%= link_to "Edit", edit_post_path(@post) %>
      <%= link_to "Delete", @post, method: :delete, data: { confirm: "Are you sure?" }%>
      <% end %>
    </div>
  </div>

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
     <div>
          <p><%= pluralize(@post.errors.count, "error") %> prevented this post from saving.</p>
          <ul>
               <% @post.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
               <% end %>
          </ul> 
     </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="/">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="nav navbar-nav mr-auto">
      <% Category.all.each do |category| %>
      <% if category.name == "Hidden" then %>
      <% else %>
      <li class="nav-item <%= 'active' if params[:category] == category.name %>">
        <%= link_to category.name, posts_path(category: category.name), class: "nav-link" %>
      </li>
      <% end %>
      <% end %>
    </ul>
    <ul class="nav navbar-nav ml-auto">
      <% if session[:admin] then %>
      <li class="nav-item %>">
        <%= link_to "posts?category=Hidden", class: "nav-link" do %>Hidden<% end %>
      </li>
      <li class="nav-item %>">
        <%= link_to new_post_path, class: "nav-link" do %>New Post<% end %>
      </li>
      <% end %>
      <li class="nav-item <%= 'active' if current_page?(about_path) %>">
        <%= link_to about_path, class: "nav-link" do %>About
        <%= (content_tag :span, "(current)", :class => "sr-only") if current_page?(about_path) %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>